version: '3'

services:
  onlifenode0:
    container_name: onlifenode0
    image: "eon/node"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - TYPE=onlife
      - LOG=${LOG:-eond.log}
    volumes:
      - ./build:/eond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  onlifenode1:
    container_name: onlifenode1
    image: "eon/node"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - TYPE=onlife
      - LOG=${LOG:-eond.log}
    volumes:
      - ./build:/eond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  onlifenode2:
    container_name: onlifenode2
    image: "onlife/node"
    environment:
      - ID=2
      - TYPE=onlife
      - LOG=${LOG:-eond.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/eond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  onlifenode3:
    container_name: onlifenode3
    image: "eon/node"
    environment:
      - ID=3
      - TYPE=onlife
      - LOG=${LOG:-eond.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/eond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

  
  validatornode0:
    container_name: validatornode0
    image: "eon/node"
    environment:
      - ID=0
      - TYPE=validator
      - LOG=${LOG:-eond.log}
    ports:
      - "26665-26666:26656-26657"
    volumes:
      - ./build:/eond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.6


  validatornode1:
    container_name: validatornode1
    image: "eon/node"
    environment:
      - ID=1
      - TYPE=validator
      - LOG=${LOG:-eond.log}
    ports:
      - "26667-26668:26656-26657"
    volumes:
      - ./build:/eond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.7

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

